parameters:
#    jar_register_for_classes.example.class: Jar\RegisterForClassesBundle\Example

services:
#    jar_register_for_classes.example:
#        class: %jar_register_for_classes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
