jar_user_homepage:
    pattern:  /admin
    defaults: { _controller: JarUserBundle:User:index }

login:
    pattern: /login
    defaults: { _controller: JarUserBundle:Security:login }

logout:
    pattern: /logout
    defaults: { _controller: JarUserBundle:Security:logout }
