parameters:
#    jar_user.example.class: Jar\UserBundle\Example

services:
#    jar_user.example:
#        class: %jar_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
